app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:    /

login_check:
    path: /login_check

logout:
    path: /logout

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

begin_test:
    path: /begin-test/
    defaults: { _controller: AppBundle:Tests:begintest, id: id }

user:
    path: /user/{id}
    defaults: { _controller: AppBundle:User:user, id: id }

account_register:
    path: /registration
    defaults: { _controller: AppBundle:Account:registration }