security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_USER:       ROLE_USER
            ROLE_ADMIN:      ROLE_ADMIN


    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username


    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        secured_area:
            pattern:  ^/
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                default_target_path: begin_test
            logout:
                path: logout
                target: login

            security: true

    access_control:
            - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
