services:
    model.user:
        class: AppBundle\Model\UserModel
        arguments: [@doctrine.orm.entity_manager, @security.context, @session]

    model.registration:
        class: AppBundle\Model\RegistrationModel
        arguments: ["@security.context", @doctrine.orm.entity_manager ,@model.user, @session]
