<?php

namespace AppBundle\Entity;

/**
 * TrueAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrueAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
